image: python:3.11

stages:
  - docs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

before_script:
  - python -m pip install --upgrade pip
  - pip install pydoctor

pages:
  stage: docs
  script:
    - make docs
    - mkdir -p public
    - cp -r doc/app-docs/* public/
  artifacts:
    paths:
      - public
  only:
    - tags
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+_docs_\d+$/'
