# NOTE: We need at least docker-compose 2.24.0 or later for the environment
# setup.
services:
  soc-ui-dev:
    image: ${REGISTRY}/${IMAGE_NAME}:latest
    container_name: ${DEPLOY_NAME}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - .:/code
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
      - path: .env_local
        required: false
    command: uvicorn app.main:app --host ${APP_INTF} --port ${APP_PORT} ${UV_ARGS}
