"""
Application config
"""

from pathlib import Path

### Serving the UI API docs
# The path to the api docs. This is generated by pydoctor
APP_DOCS_DIR = Path().absolute() / "doc/ui-api"
# This is the path relative to the root where the app API docs should be made
# available.
APP_DOCS_PATH = "app-docs"
# Whether the app docs should be mounted or not
MOUNT_APP_DOCS = True
